name: Build and Unit Test GA Provider

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'The owner of the fork'
        required: false
        default: 'modular-magician'
      repo:
        description: 'The Base Repository to pull from'
        required: false
        default: 'terraform-provider-google'
      branch:
        description: 'The branch or sha to execute against'
        required: true
      sha:
        description: "The commit to post the check result to"
        required: true

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.owner }}/${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.branch }}
        path: provider
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.19.1'
    - name: Build
      run: |
        cd provider
        go build
    - name: Lint
      run: |
        cd provider
        make lint
      if: ${{ always() }} # This step will always run, even if the previous fails
    - name: Test
      run: |
        cd provider
        make test
      id: test
      if: ${{ always() }} # This step will always run, even if the previous fails
    - uses: LouisBrunner/checks-action@v1.3.1
      if: always()
      with:
        sha: ${{ github.event.inputs.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        # token: ${{ github.token }}
        name: Second Job
        conclusion: ${{ job.status }}
        details_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        output: |
          {"summary":"${{ steps.test.outputs.summary }}"}
